# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a2935252db073b6c5df9c7108cce7c342d718d9bf16a7e0d9de6134366aabfa12f384c792a93ca9d0c27e7118eb56c44070374cb229934a4b32b0e70b3018e

test:
  secret_key_base: 08496b5c007a59ac9637c9f849e99059a6310f1998e38ed4c3c9870f4e87ef187dbfbc14aa76aa333001b466f2a4880f3daa675f29edefb24fe7d5a3fa87807a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
